version: "3"
services:
    postgres:
        image: postgres:16.0-alpine
        environment:
            POSTGRES_DB: "delivery"
            POSTGRES_USER: "delivery"
            POSTGRES_PASSWORD: "delivery"
            PGDATA: "/var/lib/postgresql/data/pgdata"
        volumes:
            - db_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"

volumes:
    db_data:
